### ISSUE TITLE
Stuck on Pulling

### ISSUE THREAD

**Issue by cori** [lostintangent/gitdoc#23] opened 2021-09-01 13:53 UTC
under some circumstances (I haven't been able to figure out what the triggers are yet) GitDoc gets stuck pulling - the status bar indicator goes to `GitDoc (Pulling...) ` and stays there indefinitely. I typically have to disable GitDoc, reënable it, and then make a specious change to trigger a checkin.

Do I have something misconfigured?

**Comment by wcerfgba** [comment] 2021-09-12 19:25
I've also been having this problem, but I also haven't been able to identify the cause. :(

**Comment by phdoerfler** [comment] 2021-10-05 10:16
I'm in the same boat. Let's compare notes to find a pattern:

- I'm on macOS, I'm using VS Code on a remote connection via ssh on linux (Ubuntu)
- When I initially connect to the remote workspace, the statusbar has "GitDoc: Pulling…" which won't go away
- I then open the terminal in VS Code, do a `git pull`, enter the password for my key and let git pull. I won't have to re-enter my password while this workspace remains connected.
- I then click on "GitDoc: Pulling…" which turns off GitDoc
- Lastly I turn GitDoc back on via the command `GitDoc: Enable` (<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
- From then on GitDoc remains in operation until I disconnect from this workspace

**Comment by cori** [comment] 2021-10-05 13:41
Similar - I'm on macOS Big Sur using VS Code 1.60.2. I am connected to a private GitHub repo remotely, but editing files that are local to my machine.

I've not tried any external git commands to see how that effects things, but disabling GitDoc by clicking its status bar indicator (the one that reads `GitDoc (pulling...)`) and then reenabling it using the Command menu seems to work; I then make a specious change and save it and within a few minutes GitDoc makes the expected commit.

**Comment by lostintangent** [comment] 2024-12-26 19:47
This should be fixed in the latest extension update.

**Closed by lostintangent** 2024-12-26 19:47 UTC
