### ISSUE TITLE
`commitOnClose` has no effect

### ISSUE THREAD

**Issue by gimbo** [lostintangent/gitdoc#21] opened 2021-07-31 17:44 UTC
(This may be a duplicate of #18 except that issue also speaks of push behaviour, which I have disabled — so I'm focussing on commit here.)

Basically, the `gitdoc.commitOnClose` setting seems to have no effect.

I've create a minimal demo repo [here](https://github.com/gimbo/gitdoc-autocommit-issue-demo) which you can clone and play with if that's helpful.

Here's its `settings.json`:

```
{
    "gitdoc.autoCommitDelay": 10000,
    "gitdoc.autoPull": "off",
    "gitdoc.autoPush": "off",
    "gitdoc.commitOnClose": true,
    "gitdoc.enabled": true,
    "gitdoc.pullOnOpen": false,
}
```

So I've disabled all the push/pull stuff, and explicitly told it to commit on close (even though that's supposedly the default behaviour). However it just doesn't seem to. It doesn't matter whether I just quit VSCode outright, or close the tab(s)/window I'm working on.

The repo contains a file `scratch.txt` which tells the story in more detail (along with the git history I suppose).

#### Version info

This is on a fresh install of VSCode (on a Mac), where GitDoc is the only installed extension.

* MacBook Pro (13-inch, M1, 2020)
* macOS Big Sur 11.5.1
* VSCode
  - Version: 1.58.2
  - Commit: c3f126316369cd610563c75b1b1725e0679adfb3
  - Date: 2021-07-14T22:10:12.490Z
  - Electron: 12.0.13
  - Chrome: 89.0.4389.128
  - Node.js: 14.16.0
  - V8: 8.9.255.25-electron.0
  - OS: Darwin arm64 20.6.0
* GitDoc v0.0.8

**Comment by BiosElement** [comment] 2022-08-14 07:20
I can also confirm this remains an issue. Happy to provide any debug information needed.

**Comment by lostintangent** [comment] 2022-11-03 23:43
Closing this as a duplicate of #18

**Closed by lostintangent** 2022-11-03 23:43 UTC
